GET http://localhost:5218/

###

GET http://localhost:5218/blogs

###

GET http://localhost:5218/blogs/1

###

POST http://localhost:5218/blogs
Content-Type: application/json

{
  "title": "My third post",
  "body": "this is my third post hee hee"
}

###

DELETE http://localhost:5218/blogs/1

###

PUT http://localhost:5218/blogs/1
Content-Type: application/json

{
  "title": "My EDITED post",
  "body": "this is my third EDITED post hee hee"
}




